services:
  isa_biosamples:
      build: 
       context: .
       dockerfile: isajson-biosamples/Dockerfile
       network: host
      ports:
        - "8032:8032"
      restart: unless-stopped
      networks:
        - host

  isa_sra:
      build: 
       context: .
       dockerfile: isajson-ena/Dockerfile
       network: host
      ports:
        - "8042:8042"
      restart: unless-stopped
      networks:
        - host

networks:
  host:
    external: true

