name: Test on Building and Pushing Docker image for BioSamples service

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: repository-services/
          file: isajson-biosamples/Dockerfile
          push: false
          tags: user/app:latest
          build-args: |
            --network host
